### ISSUE TITLE
Kotlin has been out since 2011

### ISSUE THREAD

**Issue by gilgoldzweig** [jsrn/howoldisit#120]

**Comment by DD5HT** [comment]
> In February 2012, JetBrains open sourced the project under the Apache 2 license.
> Kotlin v1.0 was released on February 15, 2016. 

So we pretty much have to discuss which date we want to use. First release date or first stable versions date.

**Comment by gilgoldzweig** [comment]
Agreed. but I think it should be the first release because people started using it and actually get experience before the stable version

**Comment by kc1r74p** [comment]
Updated date in: https://github.com/jsrn/howoldisit/pull/197
