### ISSUE TITLE
Footer Hyperlink - UX improvement 

### ISSUE THREAD

**Issue by M0nica** [jsrn/howoldisit#149]
I think that Twitter and Github in the footer should be a different color and/or underlined to differentiate them from the other text in the footer and indicate that they are clickable. If that sounds good to you I am happy to update. As right now it is hard to identify that they are clickable.

<img width="1127" alt="screen shot 2018-10-29 at 5 38 16 pm" src="https://user-images.githubusercontent.com/6998954/47682001-71c8c200-dba1-11e8-9e91-4402abc5ffa8.png">

**Comment by jsrn** [comment]
Absolutely! Please do. :)

**Comment by M0nica** [comment]
Thanks, I just submitted a PR https://github.com/jsrn/howoldisit/pull/152
