### ISSUE TITLE
Zend Framework is missing - around for 12 years

### ISSUE THREAD

**Issue by zionsg** [jsrn/howoldisit#174]
Zend Framework 0.1.1 - 2006-03-03
https://en.wikipedia.org/wiki/Zend_Framework

Zend Framework 1 - 2007-06-30
https://framework.zend.com/downloads/archives

Zend Framework 2 - 2012-09-04
https://github.com/zendframework/zendframework/releases/tag/release-2.0.0

Zend Framework 3 - 2016-06-28
https://github.com/zendframework/zendframework/releases/tag/release-3.0.0

**Comment by Esteban-Rocha** [comment]
Thanks!
