### ISSUE TITLE
Abinitio is missing

### ISSUE THREAD

**Issue by sumansarita** [jsrn/howoldisit#177]

**Comment by kc1r74p** [comment]
If you would like to add it yourself maybe create a Pull Request ? If you need help just feel free to ask here maybe we can also improve the readme.

**Comment by dantehemerson** [comment]
I saw this on Wikipedia and I think this is not a technology. I do not know if this applies to be added, otherwise we could close this.

**Comment by jsrn** [comment]
It looks like a company that makes a range of products, but it's a little tough to tell what they actually might be. Happy to close this and come back to it if there are any concrete bits of tech that can be pointed to.
