### ISSUE TITLE
 Non-fluid search

### ISSUE THREAD

**Issue by dantehemerson** [jsrn/howoldisit#178]
When I write in the search input, it gets slow every time I type a word quickly.

**Comment by jsrn** [comment]
Maybe it would help to add a slight delay to the keypress event, so it only begins the search if the user pauses typing.

**Comment by rithvikvibhu** [comment]
A few other suggestions regarding search

- Disable the browser's autocomplete
- Use a fuzzy search library like [FuseJs](http://fusejs.io/)

**Comment by dantehemerson** [comment]
@rithvikvibhu Yes, I think it's a better option

**Comment by dantehemerson** [comment]
@jsrn @rithvikvibhu  Well, I'm working on it.
 Please add the pipeline.

**Comment by jsrn** [comment]
I'm not familiar with FuseJs. Could you please expand on the benefit? Does it resolve the speed issue?
