### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by ChananelDavid** [jsrn/howoldisit#181]

**Comment by dantehemerson** [comment]
Could you be more specific?

**Comment by tcelestino** [comment]
@dantehemerson, I believe that he has said use to .json for export data instead of `export.module`.

**Comment by Esteban-Rocha** [comment]
@ChananelDavid Mind to clarify? I first though you where suggesting to add JSON but maybe is what @tcelestino pointed out?

**Comment by ChananelDavid** [comment]
@Estban-Rocha

sorry to be not specific.
What i need its adding the `JSON` creation time.
I now isnt really a language, but `XML` is here..

Sorry about my english and tnx
