### ISSUE TITLE
Java and JavaScript not sufficiently distinct

### ISSUE THREAD

**Issue by jsrn** [jsrn/howoldisit#188]
Perhaps the labels should be something like:

Java (not JavaScript!)
JavaScript (not Java!)

**Comment by kc1r74p** [comment]
Hm, not sure if this solves it.
Maybe we should hope that everyone who vists this app has at least some understanding what he or she is looking at ? Else we really need to add an extensive explanation what which technology stands for.

I guess the original proposed solution was adding the external links to the techs, but if that is not enought what could be ?
