### ISSUE TITLE
R, not displayed when typed

### ISSUE THREAD

**Issue by amrrs** [jsrn/howoldisit#214]

**Comment by samsonyuwono** [comment]
I got this

**Comment by samsonyuwono** [comment]
I actually see R being displayed when typed. Should this issue be closed?

**Comment by jsrn** [comment]
That is an interesting question, because I see R as well, but I'm not sure it's ideal that R is 80% of the way down the list after _every other language that has an R in the name_. However, I think that's a bit beyond the scope of this issue.

Thanks for taking a look!
