### ISSUE TITLE
https://howoldisit.glitch.me/ times out

### ISSUE THREAD

**Issue by sundikhin** [jsrn/howoldisit#224]
https://howoldisit.glitch.me/ times out, 504 Gateway Error

![504](https://user-images.githubusercontent.com/9601588/53687194-42fd5c80-3cf7-11e9-8cc2-535131fab4b0.png)

**Comment by jsrn** [comment]
Thank you! I've sorted it. For some reason the glitch instance was complaining about a lack of disk space, so I just cloned it from scratch.
