### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Epistol** [jsrn/howoldisit#225]
504 gateway :/

**Comment by alexlobanov** [comment]
@jsrn I think it's good idea to have some monitoring solution, like ApiChecker.com - if you don't have yet. And with status page - your site users @Epistol and myself will be in loop as well.

**Comment by jsrn** [comment]
Thanks for flagging this. I think a big part of the issue is that I'm serving a whole node app for a static page with some JS.

Soon I will try to do a static build, and then we should be able to deploy that with hopefully no further problems.

**Comment by jsrn** [comment]
It's alive! Thanks again.
