### ISSUE TITLE
Fix position of header

### ISSUE THREAD

**Issue by Anmol270900** [jsrn/howoldisit#282]
Hi everyone!
Can I make a commit for fixing the position of the header even after scrolling?

![Screenshot (367)](https://user-images.githubusercontent.com/43845658/94821010-bbba2280-041e-11eb-8718-df0da23910fc.png)

User would be able to search from here too without going back up

![Screenshot (368)](https://user-images.githubusercontent.com/43845658/94821027-c1b00380-041e-11eb-9203-896a1fdeda95.png)

**Comment by jsrn** [comment]
Hi @Anmol270900 ! I'm sorry to say that I've just merged a year-old (#265) request that does the same thing you're suggesting, so you've been beaten to the punch on this one. :(
