### ISSUE TITLE
Release date for podman

### ISSUE THREAD

**Issue by kinafu** [jsrn/howoldisit#293]
I wanted to add an entry for `podman`, but I am not sure which first release date I should pick.

Since I couldn't find an official "first release date", I looked up the history in GitHub ([https://github.com/containers/podman/network](https://github.com/containers/podman/network)). (Use keystroke [Shift] + [Left] to get to the leftmost commit.)

The [first commit](https://github.com/baude/libpod/commit/502be19aed3557ddb775fe133b095ad6e6eb87bf) dates back to April 5, 2015.
In the [podman docs](http://docs.podman.io/en/latest/markdown/podman-run.1.html#history) April, 2014 is mentioned as first date.

`{ name: "Podman", released: new Date("2015-04-05"), link: "https://podman.io" },`

**Comment by jsrn** [comment]
Hi @kinafu! Thanks for doing so much digging.

Unless you know whether or not the April 2014 date was a private release for internal use only, that's the date I'd go with.
