### ISSUE TITLE
Add popular AWS services - e.g. S3, DynamoDB etc

### ISSUE THREAD

**Issue by richbradshaw** [jsrn/howoldisit#323]
Maybe just

EC2: 25 August 2006
S3: March 14, 2006
Lambda: November 2014
DynamoDB: January 2012
RDS: 22 October 2009
CloudFront: November 18, 2008

**Comment by jsrn** [comment]
I appreciate the legwork in looking up dates, but I think I'd rather keep AWS services under a single title for now so as not to tie myself in knots making judgements on what constitutes popularity.

The rest of the list contains some pretty obscure items, so I'd prefer it not to eventually become 70% AWS offerings.

Sorry!

**Comment by alexwlchan** [comment]
Since a few people seem to be interested in a list of AWS services specifically, I forked the project and reused the template logic. There are… a lot of services. 😅  https://alexwlchan.github.io/aws-age-analyzer/

I hope you don't mind me reusing what you've built! :)

**Comment by jsrn** [comment]
@alexwlchan Heck no, that's awesome! Do you mind if I add a link to it in this project?

**Comment by alexwlchan** [comment]
> Do you mind if I add a link to it in this project?

Not at all! 😄
