### ISSUE TITLE
'years' is pluralised regardless of the count

### ISSUE THREAD

**Issue by jsrn** [jsrn/howoldisit#72]
![image](https://user-images.githubusercontent.com/1489178/47575334-c79b3100-d939-11e8-9820-7cb96a0a2b01.png)

It ought to be **1 year** and **9 years**

**Comment by Sarahjdes** [comment]
I'm starting to work on this one

**Comment by umer936** [comment]
@Sarahjdes Oh shoot. I already did two ways to do it. Haven't submitted the PR for the other way just yet. I don't mind if y'all ignore my PRs. This is nowhere near my first issue so someone with less experience can take it.

**Comment by Esteban-Rocha** [comment]
Cool then @Sarahjdes I'll be watching for your PR if you want to take over, else let us know so we can take @umer936 #73, Thank you both!

**Comment by Sarahjdes** [comment]
My PR is done! #76 

@umer936 Thanks, that's my second one

@Esteban-Rocha Maybe you can mention in the issue that people should specify they are working on something so there are not multiple folks working on it at the same time?

**Comment by jsrn** [comment]
Hi @Sarahjdes, thank you for your contribution! Since you laid claim to the issue, I'd like to accept your PR, (Sorry @umer936, @disissid, I appreciate it!)

However, #75 has the best implementation that takes the "less than a year" case into account. Could you do something like that?

**Comment by Esteban-Rocha** [comment]
@Sarahjdes Totally agreed on that one, thanks! I also will be updating the README so contributors are also aware of the [CONTRIBUTING](https://github.com/jsrn/howoldisit/blob/master/CONTRIBUTING.md) @jsrn set, thanks to (@umer936 and @disissid) for your take on this one.

**Comment by Sarahjdes** [comment]
@jsrn This is handled! I also changed the `daysSince()` for `yearsSince()`, as it made more sense. Let me know what you think of it.

@Esteban-Rocha Everyone is learning from open-source projects, both contributors and people whot started the project 💪🏻

**Comment by jsrn** [comment]
Thanks Sarah, that `daysSince()` was bugging me. I named the variable before I really knew what I was trying to do with it, and it never got fixed. 😰
