### ISSUE TITLE
Should each technology have a link to its website?

### ISSUE THREAD

**Issue by jsrn** [jsrn/howoldisit#78]
Or wikipedia page, for anything too old/obscure to have its own website?

**Comment by disissid** [comment]
+1 That's a nice feature to have.

**Comment by kc1r74p** [comment]
Not only a link, but maybe one cleanup has to be done to add correct trademark and copyright symbols to each tech name. 
This may become a problem in the future form a legal aspect.

**Comment by Zalimben** [comment]
In some cases the language does not have a website (old ones) like C or Cobol, etc, maybe a link to its wiki page for information
