### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by kc1r74p** [jsrn/howoldisit#83]
Now that the list is growing it may be nice to allow some sorting.
Maybe column based layout, so that sort order can be set by tech, date, ...
As well as keeping sort order when search is used.

**Comment by jsrn** [comment]
Not a bad idea. Being able to sort by tech date would be fun, and useful for companies that are only interest in building things with whatever the new hotness is.

**Comment by disissid** [comment]
Is anybody working on this?
